# Schema validator for the quality_control
# author: Thomas Cokelaer

type: map
mapping:
    "input_directory":
        type: str
        required: False
    "input_readtag":
        type: str
        required: False
    "input_pattern":
        type: str
        required: False
    "bam_to_fasta":
        type: map
        mapping:
           "thread":
               type: int
    "multiqc":
        type: map
        mapping:
            "options":
                type: str
            "modules":
                type: str
            "config_file":
                type: str
            "input_directory":
                type: str
    "kraken":
        type: map
        mapping:
          "do":
            type: bool
            required: True
          "thread":
            type: int
            required: True
            range: { min: 1 }
          "databases":
            type: any
            required: True




